import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Sembrando datos SST de prueba...');

  const contratistas = [
    {
      nit: '900112233',
      razonSocial: 'CONSTRUMAX S.A.S',
      representante: 'Carlos Andrés Gómez Ruiz',
      nombreComercial: 'CONSTRUMAX',
      nitDigito: '1',
      direccion: 'Cra 30 # 45-60, Bogotá',
      telefono: '6013345678',
      email: 'gerencia@construmax.com.co',
      sitioWeb: 'www.construmax.com.co',
      tipo: 'Juridica',
      tamano: 'Mediana',
      departamento: 'Bogotá',
      municipio: 'Bogotá D.C.',
      actividadEconomica: '4111 - Construcción de edificios residenciales',
      arl: 'Sura',
      nivelRiesgo: 'IV',
      vencimientoSS: '30',
      operadorPagoSS: 'SOI',
      centroEntrenamiento: 'Sena Regional Bogotá',
      consultaExamenMedico: true,
      ipsExamenes: 'IPS Salud Laboral Bogotá',
      clasificacionCategoria: 'SERVICIO DE CONSTRUCCIÓN',
      clasificacionCuadrante: 'A',
      personaContacto: 'Luisa Fernanda Torres',
      contactoAdmin: 'Juan Pablo Medina',
      actividades: 'Construcción y adecuación de obras civiles',
      costoHora: '35000',
      activo: true,
      estado: 'Activo',
      diasCorte: 30,
      permisosEspeciales: false,
      categoria1: 'CONSTRUCCION',
      categoria2: 'OBRA_CIVIL',
      categoria3: '',
      codigoSistemaExterno: 'ERP-001',
    },
    {
      nit: '800445566',
      razonSocial: 'SERVICIOS INDUSTRIALES DEL NORTE LTDA',
      representante: 'María Eugenia López Castaño',
      nombreComercial: 'SINORTE',
      nitDigito: '3',
      direccion: 'Calle 72 # 20-15, Barranquilla',
      telefono: '6053211234',
      email: 'contacto@sinorte.co',
      sitioWeb: '',
      tipo: 'Juridica',
      tamano: 'Pequeña',
      departamento: 'Atlántico',
      municipio: 'Barranquilla',
      actividadEconomica: '4321 - Instalaciones eléctricas',
      arl: 'Positiva',
      nivelRiesgo: 'III',
      vencimientoSS: '30',
      operadorPagoSS: 'Aportes en linea',
      centroEntrenamiento: '',
      consultaExamenMedico: false,
      ipsExamenes: '',
      clasificacionCategoria: 'PRESTACIÓN DE SERVICIOS',
      clasificacionCuadrante: 'B',
      personaContacto: 'Roberto Insignares',
      contactoAdmin: 'Ana Sofía Herrera',
      actividades: 'Mantenimiento eléctrico e instrumentación',
      costoHora: '28000',
      activo: true,
      estado: 'Activo',
      diasCorte: 30,
      permisosEspeciales: false,
      categoria1: 'ELECTRICO',
      categoria2: '',
      categoria3: '',
      codigoSistemaExterno: 'ERP-002',
    },
    {
      nit: '901234567',
      razonSocial: 'LOGÍSTICA Y TRANSPORTE ANDINO S.A.S',
      representante: 'Hernando Vargas Pinilla',
      nombreComercial: 'LOTANSA',
      nitDigito: '0',
      direccion: 'Av. 68 # 13-27, Bogotá',
      telefono: '6017788990',
      email: 'ops@lotansa.com',
      sitioWeb: 'www.lotansa.com',
      tipo: 'Juridica',
      tamano: 'Grande',
      departamento: 'Bogotá',
      municipio: 'Bogotá D.C.',
      actividadEconomica: '4923 - Transporte de carga por carretera',
      arl: 'AXA Colpatria',
      nivelRiesgo: 'III',
      vencimientoSS: '30',
      operadorPagoSS: 'Mi planilla',
      centroEntrenamiento: 'Centro de capacitación propio',
      consultaExamenMedico: true,
      ipsExamenes: 'Clínica del Occidente',
      clasificacionCategoria: 'CONTRATOS TODO COSTO',
      clasificacionCuadrante: 'A',
      personaContacto: 'Claudia Santamaría',
      contactoAdmin: 'Felipe Mora',
      actividades: 'Transporte de materiales y personal',
      costoHora: '22000',
      activo: true,
      estado: 'Activo',
      diasCorte: 15,
      permisosEspeciales: true,
      categoria1: 'TRANSPORTE',
      categoria2: 'LOGISTICA',
      categoria3: '',
      codigoSistemaExterno: 'ERP-003',
    },
    {
      nit: '700998877',
      razonSocial: 'MANTENIMIENTO INTEGRAL COLOMBIA S.A.',
      representante: 'Jorge Enrique Rivas Ospina',
      nombreComercial: 'MANCOL',
      nitDigito: '5',
      direccion: 'Cll 50 # 80-120, Medellín',
      telefono: '6044561234',
      email: 'info@mancol.com.co',
      sitioWeb: '',
      tipo: 'Juridica',
      tamano: 'Mediana',
      departamento: 'Antioquia',
      municipio: 'Medellín',
      actividadEconomica: '4329 - Otras instalaciones especializadas',
      arl: 'Colmena',
      nivelRiesgo: 'IV',
      vencimientoSS: '30',
      operadorPagoSS: 'SOI',
      centroEntrenamiento: 'Comfama',
      consultaExamenMedico: true,
      ipsExamenes: 'IPS Medilab',
      clasificacionCategoria: 'CONTRATOS MANO DE OBRA',
      clasificacionCuadrante: 'C',
      personaContacto: 'Diana Marcela Cano',
      contactoAdmin: 'Rodrigo Alvarado',
      actividades: 'Mantenimiento mecánico, hidráulico y civil',
      costoHora: '31000',
      activo: true,
      estado: 'Activo',
      diasCorte: 30,
      permisosEspeciales: false,
      categoria1: 'MANTENIMIENTO',
      categoria2: '',
      categoria3: '',
      codigoSistemaExterno: 'ERP-004',
    },
    {
      nit: '830561122',
      razonSocial: 'CONSULTORA SST Y MEDIO AMBIENTE SAS',
      representante: 'Patricia Inés Morales Vega',
      nombreComercial: 'CONSST',
      nitDigito: '2',
      direccion: 'Cra 15 # 93-47 Of 502, Bogotá',
      telefono: '6013321100',
      email: 'consultorias@consst.co',
      sitioWeb: 'www.consst.co',
      tipo: 'Juridica',
      tamano: 'Micro',
      departamento: 'Bogotá',
      municipio: 'Bogotá D.C.',
      actividadEconomica: '7020 - Actividades de consultoría de gestión',
      arl: 'Liberty',
      nivelRiesgo: 'I',
      vencimientoSS: '30',
      operadorPagoSS: 'Aportes en linea',
      centroEntrenamiento: '',
      consultaExamenMedico: false,
      ipsExamenes: '',
      clasificacionCategoria: 'HONORARIOS PROFESIONALES',
      clasificacionCuadrante: 'A',
      personaContacto: 'Patricia Morales',
      contactoAdmin: 'Patricia Morales',
      actividades: 'Consultoría SG-SST, auditorías y capacitaciones',
      costoHora: '85000',
      activo: true,
      estado: 'Activo',
      diasCorte: 30,
      permisosEspeciales: false,
      categoria1: 'CONSULTORIA',
      categoria2: 'SST',
      categoria3: '',
      codigoSistemaExterno: 'ERP-005',
    },
    {
      nit: '860789012',
      razonSocial: 'INGENIERÍA ELÉCTRICA Y CIVIL BOGOTÁ S.A.S',
      representante: 'Alejandro Bermúdez Forero',
      nombreComercial: 'IECBOG',
      nitDigito: '4',
      direccion: 'Av. Américas # 40-51, Bogotá',
      telefono: '6017654432',
      email: 'gerencia@iecbog.com',
      sitioWeb: '',
      tipo: 'Juridica',
      tamano: 'Pequeña',
      departamento: 'Bogotá',
      municipio: 'Bogotá D.C.',
      actividadEconomica: '4321 - Instalaciones eléctricas',
      arl: 'Sura',
      nivelRiesgo: 'III',
      vencimientoSS: '30',
      operadorPagoSS: 'SOI',
      centroEntrenamiento: '',
      consultaExamenMedico: true,
      ipsExamenes: 'Prevención en Salud IPS',
      clasificacionCategoria: 'ALQUILER DE EQUIPOS',
      clasificacionCuadrante: 'B',
      personaContacto: 'Mónica Suárez',
      contactoAdmin: 'Germán Fuentes',
      actividades: 'Diseño e instalación redes eléctricas',
      costoHora: '38000',
      activo: false,
      estado: 'Suspendido',
      diasCorte: 30,
      permisosEspeciales: false,
      categoria1: 'ELECTRICO',
      categoria2: 'INGENIERIA',
      categoria3: '',
      codigoSistemaExterno: 'ERP-006',
    },
    {
      nit: '900567890',
      razonSocial: 'ASEO Y LIMPIEZA PROFESIONAL LTDA',
      representante: 'Gloria Amparo Ríos Urrea',
      nombreComercial: 'ASELIMPRO',
      nitDigito: '7',
      direccion: 'Calle 13 # 37-18, Cali',
      telefono: '6022348899',
      email: 'operaciones@aselimpro.com',
      sitioWeb: '',
      tipo: 'Juridica',
      tamano: 'Pequeña',
      departamento: 'Valle del Cauca',
      municipio: 'Cali',
      actividadEconomica: '8121 - Actividades de limpieza de edificios',
      arl: 'Positiva',
      nivelRiesgo: 'II',
      vencimientoSS: '30',
      operadorPagoSS: 'Mi planilla',
      centroEntrenamiento: '',
      consultaExamenMedico: false,
      ipsExamenes: '',
      clasificacionCategoria: 'PRESTACIÓN DE SERVICIOS',
      clasificacionCuadrante: 'D',
      personaContacto: 'Gloria Ríos',
      contactoAdmin: 'Carlos Patiño',
      actividades: 'Servicios de aseo, desinfección y jardinería',
      costoHora: '15000',
      activo: true,
      estado: 'Activo',
      diasCorte: 30,
      permisosEspeciales: false,
      categoria1: 'SERVICIOS_GENERALES',
      categoria2: '',
      categoria3: '',
      codigoSistemaExterno: 'ERP-007',
    },
    {
      nit: '812334455',
      razonSocial: 'PROTECCIÓN Y VIGILANCIA NACIONAL S.A.',
      representante: 'Augusto Emilio Pedraza Leal',
      nombreComercial: 'PROVINA',
      nitDigito: '6',
      direccion: 'Cra 7 # 32-15, Bogotá',
      telefono: '6014432211',
      email: 'contratos@provina.com.co',
      sitioWeb: 'www.provina.com.co',
      tipo: 'Juridica',
      tamano: 'Grande',
      departamento: 'Bogotá',
      municipio: 'Bogotá D.C.',
      actividadEconomica: '8010 - Actividades de seguridad privada',
      arl: 'Alfa',
      nivelRiesgo: 'III',
      vencimientoSS: '30',
      operadorPagoSS: 'SOI',
      centroEntrenamiento: 'Escuela de entrenamiento PROVINA',
      consultaExamenMedico: true,
      ipsExamenes: 'Clínica de Marly',
      clasificacionCategoria: 'CONTRATOS TODO COSTO',
      clasificacionCuadrante: 'A',
      personaContacto: 'Beatriz Leal',
      contactoAdmin: 'Eduardo Pabón',
      actividades: 'Vigilancia, seguridad física y CCTV',
      costoHora: '18000',
      activo: true,
      estado: 'Activo',
      diasCorte: 30,
      permisosEspeciales: true,
      categoria1: 'SEGURIDAD',
      categoria2: '',
      categoria3: '',
      codigoSistemaExterno: 'ERP-008',
    },
    {
      nit: '900876543',
      razonSocial: 'OBRAS Y ACABADOS PREMIUM S.A.S',
      representante: 'Julián Camilo Castro Rojas',
      nombreComercial: 'OAPREMIUM',
      nitDigito: '9',
      direccion: 'Cll 80 # 68-25, Bogotá',
      telefono: '6018890011',
      email: 'obra@oapremium.com',
      sitioWeb: '',
      tipo: 'Juridica',
      tamano: 'Pequeña',
      departamento: 'Bogotá',
      municipio: 'Bogotá D.C.',
      actividadEconomica: '4330 - Terminación y acabado de edificios',
      arl: 'Bolívar',
      nivelRiesgo: 'IV',
      vencimientoSS: '30',
      operadorPagoSS: 'Aportes en linea',
      centroEntrenamiento: '',
      consultaExamenMedico: true,
      ipsExamenes: 'Centro Médico La Salud',
      clasificacionCategoria: 'SERVICIO DE CONSTRUCCIÓN',
      clasificacionCuadrante: 'C',
      personaContacto: 'Julián Castro',
      contactoAdmin: 'Sandra Moreno',
      actividades: 'Pintura, estucado, carpintería y acabados',
      costoHora: '25000',
      activo: true,
      estado: 'En evaluación',
      diasCorte: 30,
      permisosEspeciales: false,
      categoria1: 'CONSTRUCCION',
      categoria2: 'ACABADOS',
      categoria3: '',
      codigoSistemaExterno: 'ERP-009',
    },
    {
      nit: '805112233',
      razonSocial: 'TECNOLOGÍA Y SISTEMAS INTEGRADOS S.A.S',
      representante: 'Diana Carolina Niño Vargas',
      nombreComercial: 'TECSIS',
      nitDigito: '8',
      direccion: 'Cra 43A # 1-50, Medellín',
      telefono: '6044678912',
      email: 'soporte@tecsis.com.co',
      sitioWeb: 'www.tecsis.com.co',
      tipo: 'Juridica',
      tamano: 'Pequeña',
      departamento: 'Antioquia',
      municipio: 'Medellín',
      actividadEconomica: '6201 - Actividades de desarrollo de sistemas',
      arl: 'Liberty',
      nivelRiesgo: 'I',
      vencimientoSS: '30',
      operadorPagoSS: 'Mi planilla',
      centroEntrenamiento: '',
      consultaExamenMedico: false,
      ipsExamenes: '',
      clasificacionCategoria: 'HONORARIOS PROFESIONALES',
      clasificacionCuadrante: 'A',
      personaContacto: 'Diana Niño',
      contactoAdmin: 'Sergio Palacio',
      actividades: 'Soporte TI, redes y desarrollo de software',
      costoHora: '75000',
      activo: true,
      estado: 'Activo',
      diasCorte: 30,
      permisosEspeciales: false,
      categoria1: 'TECNOLOGIA',
      categoria2: '',
      categoria3: '',
      codigoSistemaExterno: 'ERP-010',
    },
  ];

  // Upsert contratistas SST
  const creados: { id: string; razonSocial: string }[] = [];
  for (const c of contratistas) {
    const reg = await prisma.contratistaSST.upsert({
      where: { nit: c.nit },
      update: c,
      create: c,
    });
    creados.push({ id: reg.id, razonSocial: reg.razonSocial });
    console.log(`  ✓ ${reg.razonSocial}`);
  }

  // Trabajadores por contratista (3 para los primeros 3, 2 para el resto)
  const trabajadoresBase = [
    // CONSTRUMAX (0)
    { idx: 0, documento: '1012345678', nombre: 'WILLIAM ANDRES TORRES MORA', cargo: 'MAESTRO DE OBRA', sexo: 'M', eps: 'Nueva EPS', cargo2: 'IV', estadoCivil: 'Casado', tipoVinculacion: 'ObraLabor', salario: '2000000', telefonoMovil: '3001234501', eps2: 'Nueva EPS', grupoSanguineo: 'O+', ingresoEmpresa: '2024-01-15', vencExamen: '2025-12-31', vencAlturas: '2025-06-30', habilitado: true, certRequeridas: ['Alturas', 'TrabajoEnCaliente'] },
    { idx: 0, documento: '1098765432', nombre: 'LUZ MARINA QUINTERO CASTRO', cargo: 'RESIDENTE SST', sexo: 'F', eps: 'Compensar', estadoCivil: 'Soltera', tipoVinculacion: 'TerminoFijo', salario: '4500000', telefonoMovil: '3109876501', grupoSanguineo: 'A+', ingresoEmpresa: '2024-02-01', vencExamen: '2026-02-01', vencAlturas: '2026-01-15', habilitado: true, certRequeridas: ['Alturas'] },
    { idx: 0, documento: '1034567890', nombre: 'EDGAR FABIAN MORALES NIETO', cargo: 'OFICIAL DE CONSTRUCCIÓN', sexo: 'M', eps: 'Sanitas', estadoCivil: 'Soltero', tipoVinculacion: 'ObraLabor', salario: '1700000', telefonoMovil: '3114567801', grupoSanguineo: 'B+', ingresoEmpresa: '2024-03-10', vencExamen: '2025-09-30', vencAlturas: '2025-05-31', habilitado: false, certRequeridas: ['Alturas', 'EspaciosConfinados'] },
    // SINORTE (1)
    { idx: 1, documento: '1056781234', nombre: 'RAMÓN EMILIO BARRIOS PÉREZ', cargo: 'ELECTRICISTA LÍDER', sexo: 'M', eps: 'Sura EPS', estadoCivil: 'Casado', tipoVinculacion: 'TerminoFijo', salario: '3200000', telefonoMovil: '3156781201', grupoSanguineo: 'O-', ingresoEmpresa: '2023-08-01', vencExamen: '2025-08-01', vencAlturas: '', habilitado: true, certRequeridas: ['SeguridadVial'] },
    { idx: 1, documento: '1023456789', nombre: 'VALENTINA OSPINA GUERRERO', cargo: 'TÉCNICA EN INSTRUMENTACIÓN', sexo: 'F', eps: 'Famisanar', estadoCivil: 'Union Libre', tipoVinculacion: 'Indefinido', salario: '3800000', telefonoMovil: '3123456701', grupoSanguineo: 'AB+', ingresoEmpresa: '2023-05-15', vencExamen: '2026-05-15', vencAlturas: '2025-11-30', habilitado: true, certRequeridas: ['Alturas', 'SeguridadVial'] },
    // LOTANSA (2)
    { idx: 2, documento: '1087654321', nombre: 'HERNÁN DARIO AGUIRRE SALINAS', cargo: 'CONDUCTOR LÍDER', sexo: 'M', eps: 'Compensar', estadoCivil: 'Casado', tipoVinculacion: 'Indefinido', salario: '2800000', telefonoMovil: '3107654301', grupoSanguineo: 'A-', ingresoEmpresa: '2022-04-01', vencExamen: '2025-04-01', vencAlturas: '', habilitado: true, certRequeridas: ['SeguridadVial'] },
    { idx: 2, documento: '1065432109', nombre: 'FABIOLA RUIZ OCAMPO', cargo: 'COORDINADORA LOGÍSTICA', sexo: 'F', eps: 'Salud Total', estadoCivil: 'Divorciado', tipoVinculacion: 'TerminoFijo', salario: '4200000', telefonoMovil: '3165432101', grupoSanguineo: 'B-', ingresoEmpresa: '2023-01-10', vencExamen: '2026-01-10', vencAlturas: '', habilitado: true, certRequeridas: [] },
    // MANCOL (3)
    { idx: 3, documento: '1011223344', nombre: 'ALBERTO CANO MOSQUERA', cargo: 'MECÁNICO INDUSTRIAL', sexo: 'M', eps: 'Sanitas', estadoCivil: 'Soltero', tipoVinculacion: 'ObraLabor', salario: '2500000', telefonoMovil: '3011223301', grupoSanguineo: 'O+', ingresoEmpresa: '2024-05-01', vencExamen: '2025-05-01', vencAlturas: '2025-03-31', habilitado: true, certRequeridas: ['Alturas', 'EspaciosConfinados', 'TrabajoEnCaliente'] },
    { idx: 3, documento: '1043219876', nombre: 'SANDRA MILENA ZAPATA GIRALDO', cargo: 'AUXILIAR SST', sexo: 'F', eps: 'Sura EPS', estadoCivil: 'Casada', tipoVinculacion: 'PrestacionServicios', salario: '2200000', telefonoMovil: '3043219801', grupoSanguineo: 'A+', ingresoEmpresa: '2024-06-15', vencExamen: '2025-12-31', vencAlturas: '', habilitado: true, certRequeridas: [] },
    // CONSST (4)
    { idx: 4, documento: '1000998877', nombre: 'MARTHA LUCIA VEGA OSPINA', cargo: 'PROFESIONAL SST', sexo: 'F', eps: 'Compensar', estadoCivil: 'Soltera', tipoVinculacion: 'PrestacionServicios', salario: '6500000', telefonoMovil: '3000998801', grupoSanguineo: 'O+', ingresoEmpresa: '2023-09-01', vencExamen: '2026-09-01', vencAlturas: '', habilitado: true, certRequeridas: [] },
  ];

  for (const t of trabajadoresBase) {
    const contratistaId = creados[t.idx].id;
    await prisma.trabajadorSST.upsert({
      where: { id: `sst-seed-${t.documento}` },
      update: {},
      create: {
        id: `sst-seed-${t.documento}`,
        documento: t.documento,
        nombre: t.nombre,
        cargo: t.cargo,
        sede: 'Sede Principal',
        contratistaId,
        historia: false,
        activo: true,
        habilitado: t.habilitado,
        parafiscales: true,
        certificacion: t.certRequeridas.length > 0,
        otrosCursos: false,
        induccion: true,
        empleadoActivo: true,
        fechaNacimiento: '1990-06-15',
        sexo: t.sexo,
        estadoCivil: t.estadoCivil,
        tipoVinculacion: t.tipoVinculacion,
        salario: t.salario,
        nivelEscolaridad: 'Tecnico',
        raza: 'No Aplica',
        eps: t.eps,
        telefonoMovil: t.telefonoMovil,
        grupoSanguineo: t.grupoSanguineo,
        discapacidad: 'NO',
        enfermedades: ['Ninguno'],
        transporte: 'Bus Urbano',
        ingresoEmpresa: t.ingresoEmpresa,
        vencExamen: t.vencExamen,
        vencAlturas: t.vencAlturas,
        certRequeridas: t.certRequeridas,
        accesoContratista: true,
        estadoSS: true,
        certTareas: t.certRequeridas.length > 0,
        cursoEspecifico: false,
        induccionSitio: true,
        periodicidadExamen: 365,
        accesoGeneral: t.habilitado,
        notas: '',
      },
    });
    console.log(`    ↳ ${t.nombre}`);
  }

  console.log('\n✅ Seed SST completado:');
  console.log(`   - 10 Contratistas SST`);
  console.log(`   - ${trabajadoresBase.length} Trabajadores SST`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
