-- CreateTable
CREATE TABLE "contratistas_sst" (
    "id" TEXT NOT NULL,
    "razonSocial" TEXT NOT NULL,
    "representante" TEXT,
    "nombreComercial" TEXT,
    "nit" TEXT NOT NULL,
    "nitDigito" TEXT,
    "direccion" TEXT,
    "telefono" TEXT,
    "email" TEXT,
    "sitioWeb" TEXT,
    "tipo" TEXT,
    "tamano" TEXT,
    "departamento" TEXT,
    "municipio" TEXT,
    "actividadEconomica" TEXT,
    "arl" TEXT,
    "nivelRiesgo" TEXT,
    "vencimientoSS" TEXT,
    "operadorPagoSS" TEXT,
    "centroEntrenamiento" TEXT,
    "consulta_examen_medico" BOOLEAN NOT NULL DEFAULT false,
    "ips_examenes" TEXT,
    "clasificacion_categoria" TEXT,
    "clasificacion_cuadrante" TEXT,
    "persona_contacto" TEXT,
    "contacto_admin" TEXT,
    "actividades" TEXT,
    "costo_hora" TEXT,
    "activo" BOOLEAN NOT NULL DEFAULT true,
    "actualizacion_masiva_ss" TEXT,
    "actualizacion_masiva_cursos" TEXT,
    "usuario" TEXT,
    "clave" TEXT,
    "permisos_especiales" BOOLEAN NOT NULL DEFAULT false,
    "categoria1" TEXT,
    "categoria2" TEXT,
    "categoria3" TEXT,
    "codigo_sistema_externo" TEXT,
    "estado" TEXT NOT NULL DEFAULT 'Activo',
    "dias_corte" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "contratistas_sst_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "trabajadores_sst" (
    "id" TEXT NOT NULL,
    "documento" TEXT NOT NULL,
    "nombre" TEXT NOT NULL,
    "cargo" TEXT,
    "sede" TEXT,
    "historia" BOOLEAN NOT NULL DEFAULT false,
    "activo" BOOLEAN NOT NULL DEFAULT true,
    "habilitado" BOOLEAN NOT NULL DEFAULT true,
    "parafiscales" BOOLEAN NOT NULL DEFAULT false,
    "certificacion" BOOLEAN NOT NULL DEFAULT false,
    "otros_cursos" BOOLEAN NOT NULL DEFAULT false,
    "induccion" BOOLEAN NOT NULL DEFAULT false,
    "empleado_activo" BOOLEAN NOT NULL DEFAULT true,
    "fecha_expedicion" TEXT,
    "fecha_nacimiento" TEXT,
    "sexo" TEXT,
    "estado_civil" TEXT,
    "ubicacion_fisica" TEXT,
    "tipo_vinculacion" TEXT,
    "salario" TEXT,
    "nivel_escolaridad" TEXT,
    "raza" TEXT,
    "correo" TEXT,
    "eps" TEXT,
    "direccion_residencia" TEXT,
    "telefono_residencia" TEXT,
    "telefono_movil" TEXT,
    "grupo_sanguineo" TEXT,
    "discapacidad" TEXT,
    "contacto_emergencias" TEXT,
    "telefono_emergencias" TEXT,
    "enfermedades" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "transporte" TEXT,
    "ingreso_empresa" TEXT,
    "retiro_empresa" TEXT,
    "venc_examen" TEXT,
    "venc_alturas" TEXT,
    "venc_confinados" TEXT,
    "cert_requeridas" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "acceso_contratista" BOOLEAN NOT NULL DEFAULT true,
    "estado_ss" BOOLEAN NOT NULL DEFAULT false,
    "cert_tareas" BOOLEAN NOT NULL DEFAULT false,
    "curso_especifico" BOOLEAN NOT NULL DEFAULT false,
    "induccion_sitio" BOOLEAN NOT NULL DEFAULT false,
    "fecha_revision" TEXT,
    "periodicidad_examen" INTEGER NOT NULL DEFAULT 365,
    "acceso_general" BOOLEAN NOT NULL DEFAULT true,
    "fotografia" TEXT,
    "notas" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "contratista_id" TEXT NOT NULL,

    CONSTRAINT "trabajadores_sst_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "contratistas_sst_nit_key" ON "contratistas_sst"("nit");

-- AddForeignKey
ALTER TABLE "trabajadores_sst" ADD CONSTRAINT "trabajadores_sst_contratista_id_fkey" FOREIGN KEY ("contratista_id") REFERENCES "contratistas_sst"("id") ON DELETE CASCADE ON UPDATE CASCADE;
